// Products
export const PRODUCTS_REQUEST  = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS  = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILURE  = 'PRODUCTS_FAILURE';

export const PRODUCT_REQUEST   = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS   = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE   = 'PRODUCT_FAILURE';

export const BRANDS_REQUEST    = 'BRANDS_REQUEST';
export const BRANDS_SUCCESS    = 'BRANDS_SUCCESS';
export const BRANDS_FAILURE    = 'BRANDS_FAILURE';

export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST';
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS';
export const COUNTRIES_FAILURE = 'COUNTRIES_FAILURE';

// Cart
export const CART_REQUEST      = 'CART_REQUEST';
export const CART_SUCCESS      = 'CART_SUCCESS';
export const CART_FAILURE      = 'CART_FAILURE';

// Orders
export const PICKUP_POINTS_REQUEST = 'PICKUP_POINTS_REQUEST';
export const PICKUP_POINTS_SUCCESS = 'PICKUP_POINTS_SUCCESS';
export const PICKUP_POINTS_FAILURE = 'PICKUP_POINTS_FAILURE';

export const ORDER_CREATE_REQUEST  = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS  = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE  = 'ORDER_CREATE_FAILURE';

export const ORDER_FETCH_REQUEST   = 'ORDER_FETCH_REQUEST';
export const ORDER_FETCH_SUCCESS   = 'ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAILURE   = 'ORDER_FETCH_FAILURE';
